# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5roWQdLmXFkh118tG0fhRCJdMK88201
"""

Commented out IPython magic to ensure Python compatibility.
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier

# Load the trained model
# Ensure 'titanicmodel.pkl' is in the same directory as this app.py
try:
    model = joblib.load("titanicmodel.pkl")
except FileNotFoundError:
    st.error("Error: 'titanicmodel.pkl' not found. Please ensure the model file is in the same directory.")
    st.stop()

# Load the original training data to re-fit the preprocessor
# In a real deployment, you would typically save the fitted preprocessor along with the model.
# For this example, we'll refit it on the training data loaded from 'train.csv'.
try:
    train_df = pd.read_csv("/content/train.csv")
    X_full = train_df.drop("Survived", axis=1)
except FileNotFoundError:
    st.error("Error: 'train.csv' not found. Please ensure the data file is in the same directory.")
    st.stop()

# Define features - these must match the training phase
numeric_features = [
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

categorical_features = [
    "Pclass",
    "Sex",
    "Embarked"
]

drop_columns = [
    "PassengerId",
    "Name",
    "Ticket",
    "Cabin"
]

# Drop unnecessary columns from X_full before fitting preprocessor
X_full_preprocessor_input = X_full.drop(columns=drop_columns, errors='ignore')

# Recreate the preprocessor pipeline - this must match the training phase
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

# Fit the preprocessor on the full training data features
preprocessor.fit(X_full_preprocessor_input)


st.title("Titanic Survival Prediction")
st.write("Enter passenger details to predict survival.")

# Input fields for passenger features
pclass = st.selectbox("Pclass", [1, 2, 3])
sex = st.selectbox("Sex", ["male", "female"])
age = st.slider("Age", 0, 100, 30)
sibsp = st.slider("SibSp (Siblings/Spouses Aboard)", 0, 8, 0)
parch = st.slider("Parch (Parents/Children Aboard)", 0, 6, 0)
fare = st.number_input("Fare", value=30.0, step=0.1)
embarked = st.selectbox("Embarked", ["C", "Q", "S"]) # C = Cherbourg, Q = Queenstown, S = Southampton

if st.button("Predict Survival"):
    # Create a DataFrame from inputs
    input_data = pd.DataFrame([[pclass, sex, age, sibsp, parch, fare, embarked]],
                              columns=X_full_preprocessor_input.columns) # Use the correct column order/names

    # Preprocess the input data
    processed_input = preprocessor.transform(input_data)

    # Make prediction
    prediction = model.predict(processed_input)
    prediction_proba = model.predict_proba(processed_input)

    if prediction[0] == 1:
        st.success(f"**Prediction: Survived!** (Probability: {prediction_proba[0][1]:.2f})")
    else:
        st.error(f"**Prediction: Not Survived.** (Probability: {prediction_proba[0][0]:.2f})")

st.write("---")
st.write("### Model Details:")
st.write(f"Model used: {type(model).__name__}")
st.write("Best model was trained 'Before PCA' with KNN, Accuracy: 0.8212")
